name: Publish Docker image to registry.

on:
  release:
    types: [published]

jobs:
  build_image:
    uses: ./.github/workflows/tests-pipeline.yml


  push_image:
    needs: build_image
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      attestations: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Download jar artifact
        uses: actions/download-artifact@v4
        with:
          name: msnotifications
          path: .

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: lvcvx/msnotifications

      - name: Display structure of downloaded files
        run: ls -R

      - name: Display structure of downloaded files
        run: ls



      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

